
'use strict'


// 所有的 tag 标签，全部使用单数形式
// 对于扩展的标签名，使用大驼峰格式（区别于常规标签）

/*
  组件分类：
  - HTML 标签扩展，如: CheckSwitch Dialog Toast Progress Preloader SearchBar ActionSheet
  - 经典布局 如：card list-block login-screen msg-page
    (极尽升华，仅使用一个或两个标签组合实现，可用于作为 HTML 标签的扩展)
*/

var list_tags = [
  // {
  //   "icon": "",
  //   "link": "CheckSwitch",
  //   "title": "开关",
  //   "enTitle": "CheckSwitch",
  //   "type": "plus_tags",
  // },
  // {
  //   "icon": "",
  //   "link": "Dialog",
  //   "title": "弹出提示",
  //   "enTitle": "Dialog",
  //   "type": "plus_tags",
  // },
  // {
  //   "icon": "",
  //   "link": "Toast",
  //   "title": "消息提示",
  //   "enTitle": "Toast",
  //   "type": "plus_tags",
  // },
  // {
  //   "icon": "",
  //   "link": "Progress",
  //   "title": "进度条",
  //   "enTitle": "Progress",
  //   "type": "plus_tags",
  // },
  // {
  //   "icon": "",
  //   "link": "SearchBar",
  //   "title": "搜索框",
  //   "enTitle": "SearchBar",
  //   "type": "plus_tags",
  // },
  {
    "icon": "icon-success",
    "link": "rem",
    "title": "使用rem",
    "enTitle": "1rem = 20px",
    "type": "layout",
    "badge": "new",
  },
  {
    "icon": "",
    "link": "content",
    "title": "内容区",
    "enTitle": "content",
    "type": "layout",
  },
  {
    "icon": "",
    "link": "typography",
    "title": "排版样式",
    "enTitle": "typography",
    "type": "layout",
  },
  {
    "icon": "",
    "link": "bar",
    "title": "标题栏",
    "enTitle": "Navbar",
    "type": "layout",
  },
  {
    "icon": "",
    "link": "bar",
    "title": "工具栏",
    "enTitle": " Toolbar",
    "type": "layout",
  },
  {
    "icon": "",
    "link": "icon",
    "title": "图标",
    "enTitle": "icon",
    "type": "layout",
  },
  {
    "icon": "",
    "link": "button",
    "title": "按钮",
    "enTitle": "Button",
    "type": "layout",
  },
  // {
  //   "icon": "",
  //   "link": "form",
  //   "title": "表单",
  //   "enTitle": "Form",
  //   "type": "layout",
  // },
  // {
  //   "icon": "",
  //   "link": "accordion",
  //   "title": "手风琴",
  //   "enTitle": "Accordion",
  //   "type": "layout",
  // },
  // {
  //   "icon": "",
  //   "link": "autocomplete",
  //   "title": "自动补全",
  //   "enTitle": "Autocomplete",
  //   "type": "layout",
  // },
  // {
  //   "icon": "",
  //   "link": "calendar",
  //   "title": "日历",
  //   "enTitle": "Calendar / Datepicker",
  //   "type": "layout",
  // },
  // {
  //   "icon": "",
  //   "link": "toast",
  //   "title": "消息提示框",
  //   "enTitle": "Toast",
  //   "type": "layout",
  // },
  // {
  //   "icon": "",
  //   "link": "action-sheet",
  //   "title": "操作表",
  //   "enTitle": "ActionSheet",
  //   "type": "layout",
  // },
  // {
  //   "icon": "",
  //   "link": "router",
  //   "title": "路由",
  //   "enTitle": "router",
  //   "type": "layout",
  // },
  // {
  //   "icon": "",
  //   "link": "card",
  //   "title": "卡片",
  //   "enTitle": "Card",
  //   "type": "layout",
  // },
  // {
  //   "icon": "",
  //   "link": "contact",
  //   "title": "联系人列表",
  //   "enTitle": "Contacts List",
  //   "type": "layout",
  // },
  // {
  //   "icon": "",
  //   "link": "grid",
  //   "title": "栅格",
  //   "enTitle": "Grid",
  //   "type": "layout",
  // },
  // {
  //   "icon": "",
  //   "link": "infinite-scroll",
  //   "title": "无限滚动",
  //   "enTitle": "Infinite Scroll",
  //   "type": "layout",
  // },
  // {
  //   "icon": "",
  //   "link": "lazy-load",
  //   "title": "延迟加载",
  //   "enTitle": "Lazy Load Image",
  //   "type": "layout",
  // },
  // {
  //   "icon": "",
  //   "link": "list-view",
  //   "title": "列表",
  //   "enTitle": "List View",
  //   "type": "layout",
  // },
  // {
  //   "icon": "",
  //   "link": "login-screen",
  //   "title": "登录界面",
  //   "enTitle": "Login Screen",
  //   "type": "layout",
  // },
  // {
  //   "icon": "",
  //   "link": "media-list",
  //   "title": "媒体列表",
  //   "enTitle": "Media List",
  //   "type": "layout",
  // },
  // {
  //   "icon": "",
  //   "link": "message",
  //   "title": "消息",
  //   "enTitle": "Message",
  //   "type": "layout",
  // },
  // {
  //   "icon": "",
  //   "link": "modal",
  //   "title": "对话框",
  //   "enTitle": "Modal",
  //   "type": "layout",
  // },
  // {
  //   "icon": "",
  //   "link": "notification",
  //   "title": "消息提醒",
  //   "enTitle": "Notification",
  //   "type": "layout",
  // },
  // {
  //   "icon": "",
  //   "link": "picker",
  //   "title": "选择器",
  //   "enTitle": "Picker",
  //   "type": "layout",
  // },
  // {
  //   "icon": "",
  //   "link": "datetime-picker",
  //   "title": "日期时间",
  //   "enTitle": "Datetime Picker",
  //   "type": "layout",
  // },
  // {
  //   "icon": "",
  //   "link": "city-picker",
  //   "title": "省市区",
  //   "enTitle": "City Picker",
  //   "type": "layout",
  // },
  // {
  //   "icon": "",
  //   "link": "popover",
  //   "title": "弹出提醒",
  //   "enTitle": "Popover",
  //   "type": "layout",
  // },
  // {
  //   "icon": "",
  //   "link": "preloader",
  //   "title": "加载指示器",
  //   "enTitle": "Preloader",
  //   "type": "layout",
  // },
  // {
  //   "icon": "",
  //   "link": "progressbar",
  //   "title": "进度条",
  //   "enTitle": "Progress Bar",
  //   "type": "layout",
  // },
  // {
  //   "icon": "",
  //   "link": "pull-to-refresh",
  //   "title": "下拉刷新",
  //   "enTitle": "Pull To Refresh",
  //   "type": "layout",
  // },
  // {
  //   "icon": "",
  //   "link": "searchbar",
  //   "title": "搜索栏",
  //   "enTitle": "Search Bar",
  //   "type": "layout",
  // },
  // {
  //   "icon": "",
  //   "link": "panel",
  //   "title": "侧边栏",
  //   "enTitle": "Side Panel",
  //   "type": "layout",
  // },
  // {
  //   "icon": "",
  //   "link": "sortable-list",
  //   "title": "排序列表",
  //   "enTitle": "Sortable List",
  //   "type": "layout",
  // },
  // {
  //   "icon": "",
  //   "link": "swipe-delete",
  //   "title": "滑动删除",
  //   "enTitle": "Swipe To Delete",
  //   "type": "layout",
  // },
  // {
  //   "icon": "",
  //   "link": "swiper",
  //   "title": "幻灯片",
  //   "enTitle": "Swiper Slider",
  //   "type": "layout",
  // },
  // {
  //   "icon": "",
  //   "link": "photo-browser",
  //   "title": "图片浏览器",
  //   "enTitle": "Photo Browser",
  //   "type": "layout",
  // },
  // {
  //   "icon": "",
  //   "link": "tab",
  //   "title": "Tab切换",
  //   "enTitle": "Tab",
  //   "type": "layout",
  // },
  // {
  //   "icon": "",
  //   "link": "virtual-list",
  //   "title": "虚拟列表",
  //   "enTitle": "Virtual List",
  //   "type": "layout",
  // }
];

module.exports = list_tags
